openapi: 3.0.3
info:
    title: Secret Service
    description: Keptn API for creating secrets
    version: "1.0"
servers:
    - url: http://localhost:8088
paths:
    /openapi.json:
        get:
            tags:
                - openapi
            summary: Download openapi3.json
            operationId: openapi#/openapi.json
            responses:
                "200":
                    description: File downloaded
    /secret:
        get:
            tags:
                - secret
            summary: getSecret secret
            operationId: secret#getSecret
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetSecretsResponseBody'
                            example:
                                secrets:
                                    - keys:
                                        - Perferendis et.
                                        - Voluptatem aut.
                                        - Illo et autem dolor.
                                        - Et suscipit.
                                      name: Sit est iusto ipsa.
                                      scope: Perferendis numquam voluptate.
                                    - keys:
                                        - Perferendis et.
                                        - Voluptatem aut.
                                        - Illo et autem dolor.
                                        - Et suscipit.
                                      name: Sit est iusto ipsa.
                                      scope: Perferendis numquam voluptate.
        post:
            tags:
                - secret
            summary: createSecret secret
            operationId: secret#createSecret
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateSecretRequestBody'
                        example:
                            data:
                                Blanditiis eos neque quod maiores enim vel.: Quam ullam magni quis.
                                Velit neque blanditiis repudiandae.: Qui rerum omnis.
                            name: Dolorem necessitatibus.
                            scope: Maiores labore nulla molestiae harum at voluptatem.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateSecretRequestBody'
                            example:
                                data:
                                    Facere saepe.: Omnis qui dolor.
                                    Voluptatem eos aut cupiditate.: Sint voluptas voluptatem non.
                                    Voluptatem suscipit.: Ipsam laudantium id velit hic.
                                name: Deserunt quis.
                                scope: Sed dignissimos at omnis enim.
                "409":
                    description: 'secret_already_exists: The secret already exists'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        CreateSecretRequestBody:
            type: object
            properties:
                data:
                    type: object
                    example:
                        Eos cumque porro quia cumque enim.: Repellendus rem adipisci est.
                        Qui sit ipsum rerum.: Eveniet neque nihil.
                    additionalProperties:
                        type: string
                        example: Rerum possimus nulla nostrum ipsam nemo assumenda.
                name:
                    type: string
                    example: Magnam et numquam aliquam.
                scope:
                    type: string
                    example: At aut vitae harum.
            example:
                data:
                    Nobis aperiam occaecati.: Unde debitis a.
                    Sequi necessitatibus sed amet harum et.: Qui et.
                    Sint et explicabo.: Ad ut incidunt ea sunt officia.
                name: Iste tempore.
                scope: Itaque molestiae magnam.
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        GetSecretResponseBody:
            type: object
            properties:
                keys:
                    type: array
                    items:
                        type: string
                        example: Sit magnam et quod aliquid consequuntur.
                    example:
                        - Dolores aut excepturi blanditiis eum numquam.
                        - Quo nam deserunt quod.
                        - Omnis quos rem velit.
                        - Commodi aut autem est et.
                name:
                    type: string
                    example: Repellendus provident quaerat rem perferendis dignissimos dolores.
                scope:
                    type: string
                    example: In nulla numquam excepturi et sit nesciunt.
            description: Secret result
            example:
                keys:
                    - Nesciunt ut nihil.
                    - Repellat fuga quia.
                    - Saepe neque autem quasi ipsa eum.
                    - Quis esse fuga id.
                name: Eum quis nostrum consequatur autem.
                scope: Tenetur iure et.
        GetSecretsResponseBody:
            type: object
            properties:
                secrets:
                    type: array
                    items:
                        $ref: '#/components/schemas/GetSecretResponseBody'
                    example:
                        - keys:
                            - Perferendis et.
                            - Voluptatem aut.
                            - Illo et autem dolor.
                            - Et suscipit.
                          name: Sit est iusto ipsa.
                          scope: Perferendis numquam voluptate.
                        - keys:
                            - Perferendis et.
                            - Voluptatem aut.
                            - Illo et autem dolor.
                            - Et suscipit.
                          name: Sit est iusto ipsa.
                          scope: Perferendis numquam voluptate.
                        - keys:
                            - Perferendis et.
                            - Voluptatem aut.
                            - Illo et autem dolor.
                            - Et suscipit.
                          name: Sit est iusto ipsa.
                          scope: Perferendis numquam voluptate.
            example:
                secrets:
                    - keys:
                        - Perferendis et.
                        - Voluptatem aut.
                        - Illo et autem dolor.
                        - Et suscipit.
                      name: Sit est iusto ipsa.
                      scope: Perferendis numquam voluptate.
                    - keys:
                        - Perferendis et.
                        - Voluptatem aut.
                        - Illo et autem dolor.
                        - Et suscipit.
                      name: Sit est iusto ipsa.
                      scope: Perferendis numquam voluptate.
                    - keys:
                        - Perferendis et.
                        - Voluptatem aut.
                        - Illo et autem dolor.
                        - Et suscipit.
                      name: Sit est iusto ipsa.
                      scope: Perferendis numquam voluptate.
                    - keys:
                        - Perferendis et.
                        - Voluptatem aut.
                        - Illo et autem dolor.
                        - Et suscipit.
                      name: Sit est iusto ipsa.
                      scope: Perferendis numquam voluptate.
tags:
    - name: openapi
    - name: secret
      description: The secret service can create delete or update Keptn secrets
